theme: jekyll-theme-minimal
title: Andrew Estornell
description: Interests at a glance: Algorithmic Fairness, Adversarial Machine Learning, Strategic Classification, Game Theory, Reinformcment Learning
