theme: jekyll-theme-minimal
title: Andrew Estornell
description: **Interests at a glance:** Algorithmic Fairness, Adversarial Machine Learning, Strategic Classification, Game Theory, Reinformcment Learning
github_hide: true 
show_downloads: false
github:
  zip_url: 
  another_url: 
