theme: jekyll-theme-minimal
title: Andrew Estornell
description: Interests at a glance: Algorithmic Fairness, Adversarial Machine Learning, Strategic Classification, Game Theory, Reinformcment Learning

github_hide: true 
show_downloads: false
github:
  zip_url: https://andrewEstornell.github.io/Andrew_Estornell_CV(2023).pdf
  another_url: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=SSW02WEAAAAJ&citation_for_view=SSW02WEAAAAJ:UeHWp8X0CEIC
